Updated README.md : Updated Docker Mysql Port. Installation steps are…
Yasin4261/todo-api pull request #1
Opened 2024-08-18 10:39 UTC by AhmetEminSaglik

README.md dosyasındaki kurulum adımlarını da bazı eksiklikler vardı. Sorun oluşturuyordu. Onları düzelttim Yasin Bey. Test ettim. Şuan için kurulum sorunu çözülmüş durumda. 

1-) application.properties dosyasında  3308'e bağlandığı için 
Docker ile veri tabanını başlatma adımında  port değerini "3308:3306"  olarak güncelledim.

2-) Önce Database'si çalıştırıp sonra gerekli kurulumlar yapıldığı için  database'si ayağa kaldırmayı 2. sıraya aldım.

Şuan için Windows 'da bir sorun olabilir sadece. Windows 10 için "mvnw install"  komudu çalışıyorken, "./mvnw install" komudu çalışmıyor.  OS'a bağlı bir durum olduğundan değişiklik yapmadım.

2024-08-21 01:37 UTC, Yasin4261 requested changes
Teşekkür ederim.

2024-08-21 07:51 UTC, AhmetEminSaglik commented
Rica ederim. Eğer benim comitte bir sorun yoksa PR'ı doğrudan mergeleseydin çok daha güzel olurdu. Ama sağlık olsun.

2024-08-24 08:18 UTC, Yasin4261 commented
Yapacağım, sadece kodda bazı değişiklikler yapmıştım onları pushlamadım baktığımda gayet iyiydi ekleyeceğim 🙂

2024-08-24 09:28 UTC, AhmetEminSaglik commented
Beğenmene sevindim. Kolay gelsin.

2024-09-15 16:18 UTC, merged